### ISSUE TITLE
Do I need tensorflow 1.8 and therefore python 3.6 on my system ?

### ISSUE THREAD

**Issue by ChameleonScales** [tom-doerr/TecoGAN#6]
Hi,
Sorry to bother you but I'm stuck and I wonder if I'm missing something important.
I followed the steps of the readme and could run `python3 runGan.py 0` but then when trying `python3 runGan.py 1` I got:
`ModuleNotFoundError: No module named 'tensorflow'`

Being not familiar with docker and seeing no mention of tensorflow in this repo I wonder if I'm still supposed to install it on my system.
I went to see the issues in the other repo and read that I should install version 1.8 of tensorflow but that this version can only be installed with an older python (I read 3.6 somewhere)
I would like to keep my system's python 3.8 so I tried my luck with `sudo pip install tensorflow-gpu==1.8.0` anyway but obviously got :

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.8.0
ERROR: No matching distribution found for tensorflow-gpu==1.8.0
```
So, hoping things have evolved I just tried without forcing the tensorflow-gpu version but obviously when re-trying `python3 runGan.py 1` I got:
`AttributeError: module 'tensorflow' has no attribute 'set_random_seed'`

So I wonder if I'm missing some docker command of if I just have to downgrade my system's python version to 3.6, then install tensorflow-gpu==1.8 and then things should work (or even something else).

Specs :
Ubuntu 20.04.1
Python 3.8.5
pip 20.3.3
GPU : Geforce RTX 2080 Ti
Driver Version: 455.38
CUDA Version: 11.1

**Comment by tom-doerr** [comment]
You don't need to install anything on your system, everything should be installed in the docker container.
Are you sure you ran `python3 runGan.py 1` inside the docker container and not in your normal system shell?

**Comment by tom-doerr** [comment]
You can start the container with
```
docker run --gpus all -it --mount src=$(pwd),target=/TecoGAN,type=bind -w /TecoGAN tecogan_image bash
```

**Comment by ChameleonScales** [comment]
I did run this command as specified in the steps, although it didn't seem to do much. Is it supposed to open something either in a window or the terminal ?

**Comment by tom-doerr** [comment]
No it's not supposed to open anything.

**Comment by tom-doerr** [comment]
Except of course the shell in which you have to enter `python3 runGan.py 1`. You can 't run the two commands in separate shells.

**Comment by ChameleonScales** [comment]
Actually now I get a :
`Error response from daemon: could not select device driver "" with capabilities: [[gpu]]`
when using the docker run command. It didn't do that the first time.

**Comment by ChameleonScales** [comment]
Thanks! It seems I made a mistake somewhere following the steps so I restarted from scratch and now it works. Sorry again for my ignorance.
